"""Pull reviewed notes from Notion and generate blog post drafts.

Flow:
  1. Query the Notion database for pages whose Status is "Ready for Blog".
  2. Read each page's content and assemble a structured content object.
  3. Draft a concept-first post (Claude via the Anthropic SDK when
     ANTHROPIC_API_KEY is set, otherwise a structural draft from the note).
  4. Write the draft to drafts/YYYY-MM-DD-<slug>.md with Jekyll frontmatter.
  5. Mark the Notion page Status as "Drafted".

The human then reviews the draft and moves it into site/_posts/ to publish.

Usage:
  export NOTION_API_KEY=secret_...
  export NOTION_DATABASE_ID=...
  export ANTHROPIC_API_KEY=sk-ant-...   # optional but recommended
  python scripts/notion_blog/pull_and_generate.py [--dry-run] [--limit N]
"""

from __future__ import annotations

import argparse
import datetime as dt
import logging
import os
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).parent))

import notion_api

logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]
DRAFTS_DIR = REPO_ROOT / "drafts"
PROMPT_PATH = Path(__file__).parent / "prompts" / "content_writer.md"

STATUS_READY = "Ready for Blog"
STATUS_DRAFTED = "Drafted"

# Default per the repo's documented pipeline model preference; override with
# the BLOG_MODEL environment variable (e.g. claude-sonnet-5).
DEFAULT_MODEL = "claude-sonnet-4-20250514"


def build_content_object(page: dict[str, Any]) -> dict[str, Any]:
    """Assemble the structured content object for one Notion page."""
    props = page.get("properties", {})

    def get(name: str) -> dict[str, Any]:
        return props.get(name, {})

    title = notion_api.prop_plain_text(get("Name")) or "Untitled note"
    blocks = notion_api.get_block_children(page["id"])
    body_markdown = notion_api.blocks_to_markdown(blocks)

    return {
        "page_id": page["id"],
        "title": title,
        "tags": notion_api.prop_multi_select(get("Tags")),
        "seo_keywords": notion_api.prop_multi_select(get("SEO Keywords")),
        "source": notion_api.prop_url(get("Source")),
        "notes_markdown": body_markdown,
        "notion_url": page.get("url", ""),
    }


def draft_with_claude(content: dict[str, Any]) -> tuple[str, str, str]:
    """Return (title, description, body) generated by Claude."""
    import anthropic

    client = anthropic.Anthropic()
    model = os.environ.get("BLOG_MODEL", DEFAULT_MODEL)
    system_prompt = PROMPT_PATH.read_text(encoding="utf-8")

    user_prompt = (
        "Write a blog post from this reviewed research note.\n\n"
        f"Content Topic: {content['title']}\n"
        f"SEO Keywords: {', '.join(content['seo_keywords']) or 'none provided'}\n"
        f"Source URL: {content['source'] or 'none provided'}\n\n"
        "Reviewed note content:\n\n"
        f"{content['notes_markdown']}"
    )

    response = client.messages.create(
        model=model,
        max_tokens=4096,
        system=system_prompt,
        messages=[{"role": "user", "content": user_prompt}],
    )
    text = "".join(block.text for block in response.content if block.type == "text")
    return parse_draft_response(text, fallback_title=content["title"])


def parse_draft_response(text: str, fallback_title: str) -> tuple[str, str, str]:
    title, description = fallback_title, ""
    lines = text.strip().splitlines()
    body_start = 0
    for idx, line in enumerate(lines[:4]):
        if line.startswith("TITLE:"):
            title = line[len("TITLE:") :].strip() or fallback_title
            body_start = idx + 1
        elif line.startswith("DESCRIPTION:"):
            description = line[len("DESCRIPTION:") :].strip()
            body_start = idx + 1
    body = "\n".join(lines[body_start:]).strip()
    return title, description, body


def draft_without_claude(content: dict[str, Any]) -> tuple[str, str, str]:
    """Build a structural draft straight from the note when no LLM key is set."""
    body = (
        f"{content['notes_markdown']}\n\n"
        "> Draft generated without an LLM (ANTHROPIC_API_KEY was not set).\n"
        "> Rewrite this into a ~700 word concept-first post before publishing.\n"
    )
    return content["title"], "Draft generated from reviewed research notes.", body


def slugify(title: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug[:80] or "untitled"


def write_draft(content: dict[str, Any], title: str, description: str, body: str) -> Path:
    today = dt.date.today().isoformat()
    path = DRAFTS_DIR / f"{today}-{slugify(title)}.md"
    tags = ", ".join(content["tags"]) if content["tags"] else "research"
    frontmatter = [
        "---",
        "layout: post",
        f'title: "{title.replace(chr(34), chr(39))}"',
        f'description: "{description.replace(chr(34), chr(39))}"',
        f"tags: [{tags}]",
    ]
    if content["source"]:
        frontmatter.append(f"source: {content['source']}")
    frontmatter.append("---")

    DRAFTS_DIR.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(frontmatter) + "\n\n" + body + "\n", encoding="utf-8")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Generate drafts but do not update Notion statuses",
    )
    parser.add_argument("--limit", type=int, default=0, help="Max notes to process (0 = all)")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    database_id = os.environ.get("NOTION_DATABASE_ID")
    if not database_id:
        logger.error("NOTION_DATABASE_ID is not set")
        return 1

    use_claude = bool(os.environ.get("ANTHROPIC_API_KEY"))
    if not use_claude:
        logger.warning("ANTHROPIC_API_KEY not set; drafts will be structural, not written")

    ready_filter = {"property": "Status", "select": {"equals": STATUS_READY}}
    processed = 0
    for page in notion_api.query_database(database_id, ready_filter):
        if args.limit and processed >= args.limit:
            break
        content = build_content_object(page)
        logger.info("Drafting: %s", content["title"])

        if use_claude:
            title, description, body = draft_with_claude(content)
        else:
            title, description, body = draft_without_claude(content)

        path = write_draft(content, title, description, body)
        logger.info("Wrote draft %s", path.relative_to(REPO_ROOT))

        if not args.dry_run:
            notion_api.update_page_properties(
                content["page_id"],
                {"Status": {"select": {"name": STATUS_DRAFTED}}},
            )
            logger.info("Marked Notion page as %s", STATUS_DRAFTED)
        processed += 1

    if processed == 0:
        logger.info("No notes with Status = %r found; nothing to do", STATUS_READY)
    else:
        logger.info(
            "Done: %d draft(s) in drafts/. Review, edit, then move to site/_posts/ to publish.",
            processed,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
